### ISSUE TITLE
Misplaced atm_status.xml

### ISSUE THREAD

**Issue by teobais** [ozkansari/atmstatemachine#1]
Hello,

the current implementation explodes in runtime with the following error:

<code>Exception in thread "main" java.lang.IllegalArgumentException: Cannot parse null URL
    at org.apache.commons.scxml.io.SCXMLParser.parse(SCXMLParser.java:155)
    at org.apache.commons.scxml.env.AbstractStateMachine.<init>(AbstractStateMachine.java:123)
    at org.apache.commons.scxml.env.AbstractStateMachine.<init>(AbstractStateMachine.java:103)
    at net.javafun.example.atmstatusfsm.AtmStatusFSM.<init>(AtmStatusFSM.java:29)
    at net.javafun.example.atmstatusfsm.AtmDisplay.<init>(AtmDisplay.java:31)
    at net.javafun.example.atmstatusfsm.AtmDisplay.main(AtmDisplay.java:26)
</code>

What worked for me, without further changes, is:

<ol><li>Moving the <code>atm_status.xml</code>, under the <code>/src</code> folder</li><li>Renaming its declaration to
 <code>private static final String SCXML_CONFIG_ATM_STATUS = "atm_status.xml";</code></li></ol>

**Comment by ozkansari** [comment]
Thanks. I'll check this ASAP.

**Comment by codeashcode** [comment]
@toubou91 this doesn't work for me. I am still getting same error.

**Comment by ozkansari** [comment]
I've converted to project into maven. This should fix the problem.
